### ISSUE TITLE
Fix Aluminium Ore recipes

### ISSUE THREAD

**Issue by GGG-KILLER** [notcake/glua-minecraft-config#15]
This is a continuation to #12.

After having #14 merged into the repo, compressed/nether/end aluminium ores, after being processed, result in Ore Core's Aluminium Ore, which has no processing recipes.

There might be more compressed/nether/end ores that need fixing, the aluminium ones are the only ones I've stumbled upon for now.

EDIT: One of the solutions I thought of was prioritizing ores from certain mods (`minecraft`, `mekanism`, etc.) but that wouldn't solve aluminum (because of the naming issue: alumin_**i**_um vs. aluminum)

**Comment by mcd1992** [comment]
No orecore this year.
