### ISSUE TITLE
[GLua MC 2019] Disable long range teleportation devices

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-config#6]
**Mod Name**|**Teleport Type**|**Item Name**|**Should Disable? (Y/N)**|**Notes**
:-----:|:-----:|:-----:|:-----:|:-----:
Cyclic|Arbitrary Long Range|Ender Book|Y| 
Draconic Evolution|Arbitrary Long Range|Dislocator|Y| 
"|Arbitrary Long Range|Advanced Dislocator|Y| 
"|Fixed Long Range|Dislocator Receptacle|Y| 
Ender IO|Fixed Long Range|Dimensional Transceiver|Y|Can be used to teleport players in minecarts
"|Arbitrary Long Range|Telepad Block|Y| 
"|Fixed Long Range|Travel Anchor|Y| 
IndustrialCraft|Fixed Long Range|Teleporter|Y| 
Mekanism|Fixed Long Range|Teleporter Frame|Y| 
"|Fixed Long Range|Portable Teleporter|Y| 
Project Red|Fixed Long Range|Teleposer|Y| 
RFTools|Fixed Long Range|Matter Receiver|Y| 
Thermal Expansion|Fixed Long Range|Teleport Plate|Y| 
FTB Utilities|Arbitrary Long Range|/home etc.|Y| 
Random Things|Fixed Long Range|Floo Dust / Floo Sign|Y| 
Reliquiary|Fixed Long Range|Wraith Node|Y| 
Waystones|Fixed Long Range|Warp Scroll|Y| 
"|Fixed Long Range|Return Scroll|Y| 
"|Fixed Long Range|Bound Scroll|Y| 
"|Fixed Long Range|Waystone|Y|Just disable player crafting. They can still spawn in the world

**Comment by notcake** [comment]
We will have to re-enable Railcraft!

**Comment by notcake** [comment]
If this gets done please do the disabling across all mod configs in a single commit so that it can be easily reverted for future minecrafts.

**Comment by SwadicalRag** [comment]
TODO: figure out if `Rift signature` from DimensionalDoors needs to be removed
